FROM python:3.13-alpine

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./api /code/app

EXPOSE 8080

CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "8080"]